# Generated by Django 4.1.1 on 2022-09-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatepage',
            name='slug',
        ),
    ]
